kind: pipeline
type: docker
name: default

steps:
- name: install
  image: composer
  commands:
  - composer install

- name: test
  image: php:8.0
  commands:
  - php artisan test

- name: docker
  image: plugins/docker
  settings:
    repo: registry.ad-impeldown.synology.me/op-api
    registry: registry.ad-impeldown.synology.me
    storage_driver: vfs
    tags:
      - latest
